### ISSUE TITLE
Google Drive link has expired

### ISSUE THREAD

**Issue by xxzyyds** [JackLin95/Autonomous-Ultrasound-CodeData#1]

**Comment by MuyangLin95** [comment]
The image data sets for classification models can be accessed via google drive (https://drive.google.com/drive/folders/1Q9n6q3YMMSf6ZsZNJtvClwhCxYuUAXUa?usp=sharing).
The image data sets for MECA model can be accessed via google drive (https://drive.google.com/drive/folders/1gYUCoLMNrgQ1eqeNru_aTUm1eVJKYX9M?usp=sharing).
The image datasets for logistic model can be accessed via google drive (https://drive.google.com/drive/folders/1KbXbwZMpBy4o0lzAVu0aRIIBq_h4AzQS?usp=sharing).
